export const shiftHours = {
    "Morning": [
        "5:00 AM",
        "5:30 AM",
        "6:00 AM",
        "6:30 AM",
        "7:00 AM",
        "7:30 AM",
        "8:00 AM",
        "8:30 AM",
        "9:00 AM",
        "9:30 AM",
        "10:00 AM",
        "10:30 AM",
        "11:00 AM"
    ],
    "Mid": [
        "11:00 AM",
        "11:30 AM",
        "12:00 PM",
        "12:30 PM",
        "1:00 PM",
        "1:30 PM",
        "2:00 PM",
        "2:30 PM",
        "3:00 PM",
        "3:30 PM",
        "4:00 PM",
        "4:30 PM",
        "5:00 PM"
    ],
    "Night": [
        "5:00 PM",
        "5:30 PM",
        "6:00 PM",
        "6:30 PM",
        "7:00 PM",
        "7:30 PM",
        "8:00 PM",
        "8:30 PM",
        "9:00 PM",
        "9:30 PM",
        "10:00 PM",
        "10:30 PM",
        "11:00 PM"
    ]
};

export const positions = [
    "Drive Shots",
    "Line Buster 1",
    "Drive Milk",
    "Walkup Shots",
    "Window",
    "Walkup Milk",
    "Line Buster 2",
    "Pit 1",
    "Sidebar Shots",
    "Line Buster 3",
    "Sidebar Milk",
    "Pit 2",
    "Drink Runner",
    "Flow Master",
    "Walkup Window"
];

export const broistaData = {
    "Owens": [
        "Brady Anderton",
        "Clay O'Dell",
        "Emily Haney",
        "Emma Jordan",
        "Gerrit Rempfer",
        "Grace Chambers",
        "Holland Lawless",
        "Ivy Ames",
        "Jonathan McAteer",
        "Kai Lockhart",
        "Katie Chen",
        "Kiana Rayas",
        "Laura Morgan",
        "Mikayla Sotelo",
        "Anne Kusserow",
        "Riley Henze",
        "Sophia Hubbard",
        "Stella Foreman",
        "Kayla Agnew",
        "Michael Fameli"
    ],
    "University": [
        "Brooklyn Lazenby",
        "Carley White",
        "Clayton Thole",
        "Declan Montgomery",
        "Emily Kiengkham",
        "Faith Pouliot",
        "Jada Chiu",
        "Lauren Sithole",
        "Lilly Teer",
        "Lydia Sitlinger",
        "Marlee Sherman Samuel",
        "Megan Davis",
        "Rayne Swiger",
        "Reginae Gary",
        "Andrew Christiansen",
        "Megan Skoko",
        "Nae Gary",
        "Sydnii Arthur",
        "Sage Simpson",
        
    ]
};

export const allShiftHours = [
        "5:00 AM",
        "5:30 AM",
        "6:00 AM",
        "6:30 AM",
        "7:00 AM",
        "7:30 AM",
        "8:00 AM",
        "8:30 AM",
        "9:00 AM",
        "9:30 AM",
        "10:00 AM",
        "10:30 AM",
        "11:00 AM",
        "11:30 AM",
        "12:00 PM",
        "12:30 PM",
        "1:00 PM",
        "1:30 PM",
        "2:00 PM",
        "2:30 PM",
        "3:00 PM",
        "3:30 PM",
        "4:00 PM",
        "4:30 PM",
        "5:00 PM",
        "5:30 PM",
        "6:00 PM",
        "6:30 PM",
        "7:00 PM",
        "7:30 PM",
        "8:00 PM",
        "8:30 PM",
        "9:00 PM",
        "9:30 PM",
        "10:00 PM",
        "10:30 PM",
        "11:00 PM",
        "11:30 PM"

]